# Generated by Django 3.2.9 on 2021-11-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('quotes_title', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('quotes_auth', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='project')),
                ('description', models.TextField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('client', models.CharField(default='', max_length=150)),
                ('url', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('img', models.ImageField(upload_to='project')),
                ('logo', models.ImageField(default='', upload_to='project')),
                ('view_count', models.BigIntegerField(default=0)),
                ('facebook', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(editable=False)),
                ('create_date', models.DateField(editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='project.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
        migrations.AddField(
            model_name='parameter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project'),
        ),
    ]
