# Generated by Django 3.2.9 on 2021-11-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211121_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sub_title', models.CharField(default='', max_length=250)),
                ('anim_img', models.ImageField(upload_to='service')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
