# Generated by Django 3.2.9 on 2021-12-01 06:51

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectconfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfigure',
            name='bg_hover_box_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='projectconfigure',
            name='bg_icon_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='projectconfigure',
            name='bg_icon_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='projectconfigure',
            name='hover_box_opacity',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='projectconfigure',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='projectconfigure',
            name='icon_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
