# Generated by Django 3.2.9 on 2021-12-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectconfigure_bg_btn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectconfigure',
            old_name='bg_btn',
            new_name='bg_btn_color',
        ),
    ]
