# Generated by Django 3.2.9 on 2021-12-01 08:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_bg_btn_projectconfigure_bg_btn_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfigure',
            name='bg_btn_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
