# Generated by Django 3.2.9 on 2021-12-01 08:41

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_projectconfigure_bg_btn_hover_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfigure',
            name='bg_btn_filter_active_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='projectconfigure',
            name='btn_filter_active_hover_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='projectconfigure',
            name='filter_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
