# Generated by Django 3.1.7 on 2021-10-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=250)),
                ('title', models.CharField(default='Tech Leo || Your best choice', max_length=250)),
                ('sub_title', models.CharField(max_length=250)),
                ('facebook', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('about', models.TextField()),
                ('descriptions', models.TextField(default='', max_length=1000)),
                ('icon', models.ImageField(upload_to='company')),
                ('logo', models.ImageField(upload_to='company')),
                ('footer_logo', models.ImageField(default='', upload_to='company')),
                ('video_img', models.ImageField(default='', upload_to='company')),
                ('opening_day', models.CharField(default='', max_length=250)),
                ('opening_time', models.CharField(default='', max_length=250)),
                ('video', models.CharField(default='', max_length=250)),
                ('opening_holiday', models.CharField(default='', max_length=250)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
