# Generated by Django 3.1.7 on 2021-10-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('post_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
