# Generated by Django 3.1.7 on 2021-10-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='query',
            new_name='message',
        ),
    ]
