# Generated by Django 3.1.7 on 2021-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20211025_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
