# Generated by Django 3.2 on 2021-11-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='opening_holiday',
            new_name='holiday',
        ),
    ]
