# Generated by Django 3.2 on 2021-11-06 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_opening_holiday_companyinfo_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='last_name',
        ),
    ]
