# Generated by Django 3.2.9 on 2021-11-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
