# Generated by Django 3.2.9 on 2021-11-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_faq_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='is_active',
            new_name='active',
        ),
    ]
