# Generated by Django 3.2.9 on 2021-11-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_contactconfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
