# Generated by Django 3.2.9 on 2021-11-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_companyinfo_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactconfigure',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
