# Generated by Django 3.2.9 on 2021-11-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_contactconfigure_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeFactsConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(default='', upload_to='fact')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
