# Generated by Django 3.2.9 on 2021-11-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_somefactsconfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='somefactsconfigure',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
