# Generated by Django 3.2.9 on 2021-11-28 09:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_somefactsconfigure_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='bg_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='slider',
            name='bg_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
