# Generated by Django 3.2.9 on 2021-11-28 09:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20211128_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesliderconfigure',
            name='bg_btn_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='homesliderconfigure',
            name='bg_btn_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
