# Generated by Django 3.2.9 on 2021-11-28 09:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20211128_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesliderconfigure',
            name='bg_play_btn_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
