# Generated by Django 3.2.9 on 2021-11-29 06:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20211128_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesliderconfigure',
            name='social_box_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
