# Generated by Django 3.2.9 on 2021-12-01 06:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20211201_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='icon_active_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='faq',
            name='icon_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
