# Generated by Django 3.2.9 on 2021-12-01 06:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_auto_20211201_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(upload_to='video')),
                ('title_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('icon_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('icon_active_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='faq',
            name='icon_active_color',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='icon_color',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='title_color',
        ),
    ]
