# Generated by Django 3.2.9 on 2021-12-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20211201_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqconfigure',
            old_name='title_color',
            new_name='title_active_color',
        ),
    ]
