# Generated by Django 3.2.9 on 2021-12-01 11:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_rename_title_color_faqconfigure_title_active_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactconfigure',
            name='bg_contact_config_icon_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='contactconfigure',
            name='bg_contact_config_icon_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='contactconfigure',
            name='contact_config_icon_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='contactconfigure',
            name='contact_form_icon_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
