# Generated by Django 3.2.9 on 2021-12-01 11:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_auto_20211201_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactconfigure',
            old_name='btn_txt_color',
            new_name='btn_contact_form_txt_color',
        ),
        migrations.AddField(
            model_name='contactconfigure',
            name='btn_contact_form_txt_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
