# Generated by Django 3.2.9 on 2021-11-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20211121_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='is_two_columns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parameter',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
