# Generated by Django 3.2.9 on 2021-11-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20211121_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='img',
            new_name='icon',
        ),
    ]
