# Generated by Django 3.2.9 on 2021-11-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_rename_img_service_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='is_two_columns',
        ),
    ]
