# Generated by Django 3.2.9 on 2021-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_parameter_is_two_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('img', models.ImageField(upload_to='service')),
                ('bg', models.ImageField(upload_to='service')),
                ('anim_img', models.ImageField(upload_to='service')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
