# Generated by Django 3.2.9 on 2021-11-29 06:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_serviceconfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigure',
            name='dot_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
