# Generated by Django 3.2.9 on 2021-12-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20211201_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='learn_more_btn_txt',
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='learn_more_btn_txt',
            field=models.CharField(default='', max_length=50),
        ),
    ]
