# Generated by Django 3.2.9 on 2021-12-01 10:26

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_serviceconfigure_learn_more_btn_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigure',
            name='bg_item_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='bg_item_end_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='bg_item_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='bg_item_start_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
