# Generated by Django 3.2.9 on 2021-12-01 10:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20211201_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigure',
            name='btn_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='btn_end_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='btn_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='btn_start_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
