# Generated by Django 3.2.9 on 2021-12-01 10:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_auto_20211201_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceconfigure',
            name='btn_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='serviceconfigure',
            name='btn_txt_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
