# Generated by Django 3.2 on 2021-11-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='quotes_auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='quotes_title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
