# Generated by Django 3.2 on 2021-11-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211118_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='title',
        ),
    ]
