# Generated by Django 3.2 on 2021-11-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_parameter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='title',
        ),
    ]
