# Generated by Django 3.2 on 2021-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_parameter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sort_description',
            field=models.TextField(default=''),
        ),
    ]
