# Generated by Django 3.2.9 on 2021-12-01 11:42

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btn_start_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('btn_end_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('btn_start_hover_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('btn_end_hover_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('btn_txt_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('btn_txt_hover_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('item_calender_icon_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
