# Generated by Django 3.2 on 2021-10-29 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='team')),
                ('facebook', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('team_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='about.teamconfigure')),
            ],
        ),
    ]
