# Generated by Django 3.2 on 2021-10-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('designation', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False)),
                ('post_date', models.DateField(editable=False)),
                ('image', models.ImageField(upload_to='client_image')),
            ],
        ),
    ]
