# Generated by Django 3.2 on 2021-10-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='video_config')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='client_image')),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
