# Generated by Django 3.2 on 2021-10-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20211030_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoconfig',
            name='image',
        ),
    ]
