# Generated by Django 3.2 on 2021-11-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='great_support',
        ),
        migrations.RemoveField(
            model_name='about',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title',
        ),
        migrations.AddField(
            model_name='about',
            name='active_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='best_security',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='glorious_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='growth_revenue',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='projects_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='risk_manage',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='team_members',
            field=models.IntegerField(default=0),
        ),
    ]
