# Generated by Django 3.2.9 on 2021-11-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20211120_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='img',
            field=models.ImageField(default='', upload_to='mission'),
        ),
    ]
