# Generated by Django 3.2.9 on 2021-11-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_about_expert_team_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
