# Generated by Django 3.2.9 on 2021-11-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_about_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(default='', upload_to='who_we_are')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='about.missionconfigure'),
        ),
    ]
