# Generated by Django 3.2.9 on 2021-11-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_auto_20211124_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='why_us_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='why_us', to='about.whyusconfigure'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
