# Generated by Django 3.2.9 on 2021-11-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_auto_20211124_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyUs',
        ),
    ]
