# Generated by Django 3.2.9 on 2021-11-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_whyus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(default='', upload_to='about')),
                ('count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
