# Generated by Django 3.2.9 on 2021-11-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_counter_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='white_img',
            field=models.ImageField(default='', upload_to='about'),
        ),
    ]
