# Generated by Django 3.2.9 on 2021-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_feature_white_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionconfigure',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
