# Generated by Django 3.2.9 on 2021-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_missionconfigure_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyusconfigure',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
