# Generated by Django 3.2.9 on 2021-11-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_whyusconfigure_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='best_security',
        ),
        migrations.RemoveField(
            model_name='about',
            name='expert_team_work',
        ),
        migrations.RemoveField(
            model_name='about',
            name='great_support',
        ),
        migrations.RemoveField(
            model_name='about',
            name='growth_revenue',
        ),
        migrations.RemoveField(
            model_name='about',
            name='risk_manage',
        ),
    ]
