# Generated by Django 3.2.9 on 2021-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_auto_20211125_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='howwedoitconfigure',
            name='sub_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
