# Generated by Django 3.2.9 on 2021-11-29 05:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0025_howwedoitconfigure_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyusconfigure',
            name='bg_btn_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='whyusconfigure',
            name='bg_btn_hov_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='whyusconfigure',
            name='bg_btn_hov_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='whyusconfigure',
            name='bg_btn_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='whyusconfigure',
            name='bg_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='whyusconfigure',
            name='bg_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
