# Generated by Django 3.2.9 on 2021-11-29 06:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0026_auto_20211129_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='counter_border_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='feature',
            name='counter_text_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
