# Generated by Django 3.2.9 on 2021-11-29 06:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0027_auto_20211129_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='feature',
            name='radius',
            field=models.IntegerField(default=50),
        ),
    ]
