# Generated by Django 3.2.9 on 2021-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0028_auto_20211129_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='border_width',
            field=models.IntegerField(default=10),
        ),
    ]
