# Generated by Django 3.2.9 on 2021-11-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0029_feature_border_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyusconfigure',
            name='bg_img',
            field=models.ImageField(default='', upload_to='about'),
        ),
    ]
