# Generated by Django 3.2.9 on 2021-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0031_auto_20211129_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='howwedoitconfigure',
            name='steps_section_2_img',
            field=models.ImageField(default='', upload_to='how_to_do_it'),
        ),
        migrations.AddField(
            model_name='howwedoitconfigure',
            name='steps_section_3_img',
            field=models.ImageField(default='', upload_to='how_to_do_it'),
        ),
    ]
