# Generated by Django 3.2.9 on 2021-12-01 10:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0035_howwedoitconfigure_item_icon_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialconfigure',
            name='bg_bottom_line_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='testimonialconfigure',
            name='bg_bottom_line_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='testimonialconfigure',
            name='bg_item_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='testimonialconfigure',
            name='description_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='testimonialconfigure',
            name='designation_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='testimonialconfigure',
            name='title_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
