# Generated by Django 3.2 on 2021-10-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0002_relatedworkconfigure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner')),
            ],
        ),
    ]
