# Generated by Django 3.2.9 on 2021-11-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0003_pagebanner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChooseUsConfigure',
            new_name='WhoWeAreConfigure',
        ),
        migrations.RenameModel(
            old_name='PortfoliosConfigure',
            new_name='WhyChooseUsConfigure',
        ),
    ]
