# Generated by Django 3.2.9 on 2021-11-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0004_auto_20211122_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogConfigure',
            new_name='SomeFactsConfigure',
        ),
        migrations.DeleteModel(
            name='ClientConfigure',
        ),
        migrations.AddField(
            model_name='videoconfigure',
            name='img',
            field=models.ImageField(default='', upload_to='video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoconfigure',
            name='video',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
