# Generated by Django 3.2.9 on 2021-11-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0005_auto_20211122_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedWorkConfigure',
        ),
    ]
