# Generated by Django 3.2.9 on 2021-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0006_delete_relatedworkconfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebanner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
