# Generated by Django 3.2.9 on 2021-11-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0008_auto_20211123_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoweareconfigure',
            name='img',
            field=models.ImageField(default='', upload_to='who_we_are'),
        ),
    ]
