# Generated by Django 3.2.9 on 2021-11-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0013_somefactsconfigure_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconfigure',
            name='bg',
            field=models.ImageField(default='', upload_to='video'),
        ),
    ]
