# Generated by Django 3.2.9 on 2021-11-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0014_videoconfigure_bg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='video')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
