# Generated by Django 3.2.9 on 2021-11-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0015_faqconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhoWeAreConfigure',
        ),
    ]
