# Generated by Django 3.2.9 on 2021-11-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0016_delete_whoweareconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestimonialConfigure',
        ),
    ]
