# Generated by Django 3.2.9 on 2021-11-24 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0017_delete_testimonialconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowWeDoItConfigure',
        ),
    ]
