# Generated by Django 3.2.9 on 2021-11-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0018_delete_howwedoitconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhyChooseUsConfigure',
        ),
    ]
