# Generated by Django 3.2.9 on 2021-11-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0019_delete_whychooseusconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactConfigure',
        ),
    ]
