# Generated by Django 3.2.9 on 2021-11-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0020_delete_contactconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceConfigure',
        ),
    ]
