# Generated by Django 3.2.9 on 2021-11-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0021_delete_serviceconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeFactsConfigure',
        ),
    ]
