# Generated by Django 3.2.9 on 2021-11-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0023_faqconfigure_sub_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSliderConfigure',
        ),
    ]
