# Generated by Django 3.2.9 on 2021-12-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0024_delete_homesliderconfigure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaqConfigure',
        ),
    ]
