# Generated by Django 3.2.9 on 2021-12-01 07:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0025_delete_faqconfigure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_to_top_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('back_to_top_after_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('back_to_top_before_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('back_to_top_txt_hover_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('back_to_top_txt_focus_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
