# Generated by Django 3.2.9 on 2021-12-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0027_auto_20211201_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetup',
            name='title_icon',
            field=models.ImageField(default='', upload_to='page_setup'),
        ),
    ]
