# Generated by Django 3.2.9 on 2021-12-01 08:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0029_auto_20211201_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconfigure',
            name='btn_hov_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='videoconfigure',
            name='btn_txt_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
