# Generated by Django 3.2.9 on 2021-12-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0030_auto_20211201_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoconfigure',
            name='btn_hov_txt_color',
        ),
    ]
