# Generated by Django 3.2.9 on 2021-12-01 09:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0031_remove_videoconfigure_btn_hov_txt_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconfigure',
            name='border_play_btn_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='videoconfigure',
            name='triangle_play_btn_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
