# Generated by Django 3.2.9 on 2021-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0032_auto_20211201_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconfigure',
            name='border_width',
            field=models.IntegerField(default=0),
        ),
    ]
