# Generated by Django 3.2.9 on 2021-12-01 11:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0033_videoconfigure_border_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetup',
            name='sidebar_search_btn_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='pagesetup',
            name='sidebar_search_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
