# Generated by Django 3.2.9 on 2021-12-01 11:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0034_auto_20211201_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetup',
            name='pagination_btn_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='pagesetup',
            name='pagination_btn_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
