# Generated by Django 3.2.9 on 2021-12-01 12:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0035_auto_20211201_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetup',
            name='quote_btn_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='pagesetup',
            name='quote_btn_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
