# Generated by Django 3.2.9 on 2021-12-01 12:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0036_auto_20211201_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagesetup',
            old_name='quote_btn_color',
            new_name='quote_btn_one_color',
        ),
        migrations.RenameField(
            model_name='pagesetup',
            old_name='quote_btn_hover_color',
            new_name='quote_btn_one_hover_color',
        ),
        migrations.AddField(
            model_name='pagesetup',
            name='quote_btn_two_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='pagesetup',
            name='quote_btn_two_hover_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
