# Generated by Django 3.2.9 on 2021-12-01 12:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0037_auto_20211201_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesetup',
            name='bg_footer_end_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='pagesetup',
            name='bg_footer_start_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
